// web/src/lib/JobPanel.svelte
<script lang="ts">
  import { Button, ProgressBar } from '@immich/ui';
  import { mdiContentCopy, mdiStop } from '@mdi/js';
  import { thumbnail, type JobView } from './api';
  import { t } from './i18n.svelte';

  let { job, onCancel }: { job: JobView; onCancel: () => void } = $props();

  let now = $state(Date.now());
  let output = $state('');
  let copied = $state(false);

  $effect(() => {
    if (job.status !== 'running') return;
    const timer = setInterval(() => (now = Date.now()), 1000);
    return () => clearInterval(timer);
  });

  // A failed job says why in the child's own words.
  $effect(() => {
    if (job.status !== 'failed' && job.status !== 'interrupted') return;
    void fetch(`/api/v1/jobs/${encodeURIComponent(job.id)}/output`)
      .then((response) => response.json())
      .then((body) => (output = String(body.output ?? '').split('\n').slice(-25).join('\n')));
  });

  const elapsed = $derived.by(() => {
    const seconds = Math.max(0, Math.round(((job.finished_at ?? now / 1000) - job.started_at)));
    const minutes = Math.floor(seconds / 60);
    return minutes ? `${minutes}m ${String(seconds % 60).padStart(2, '0')}s` : `${seconds}s`;
  });
  const fraction = $derived(job.progress.fraction ?? null);
  // The whole job's estimate when a finished run measured it; a first cut only has its stage's.
  // Rounded on purpose, as the terminal rounds it: an estimate, not a countdown.
  const remaining = $derived.by(() => {
    const total = job.progress.remaining_seconds;
    const stage = job.progress.stage_remaining_seconds;
    const seconds = total ?? stage;
    if (seconds == null) return '';
    const amount = seconds < 60 ? `${Math.ceil(seconds)}s` : `${Math.ceil(seconds / 60)}m`;
    return total != null ? t('About {amount} left', { amount }) : t('~{amount} left in this stage', { amount });
  });

  async function copy() {
    await navigator.clipboard.writeText(job.command);
    copied = true;
    setTimeout(() => (copied = false), 1500);
  }
</script>

<section class="flex flex-col gap-4 rounded-2xl border border-gray-200 p-5 dark:border-gray-800" aria-live="polite" aria-label={t('Progress')}>
  <div class="flex flex-wrap items-center justify-between gap-3">
    <p class="font-medium">
      {#if job.status === 'running'}{job.progress.label || t('Starting')}
      {:else if job.status === 'succeeded'}{job.kind === 'cut' ? t('The cut is ready.') : t('The film is ready.')}
      {:else if job.status === 'cancelled'}{t('Stopped.')}
      {:else}{t('It did not finish.')}{/if}
    </p>
    <span class="text-sm text-gray-600 tabular-nums dark:text-gray-400">{elapsed}</span>
  </div>

  {#if job.status === 'running'}
    <ProgressBar value={fraction ?? 0} valueLabel={fraction == null ? job.progress.label : `${Math.round(fraction * 100)}%`} aria-label={t('Progress')} />
    {#if remaining}<p class="text-sm text-gray-600 dark:text-gray-400">{remaining}</p>{/if}
    {#if job.progress.total}
      <p class="text-sm text-gray-600 tabular-nums dark:text-gray-400">
        {t('{done} of {total}', { done: job.progress.done ?? 0, total: job.progress.total })}
      </p>
    {/if}
    {#if job.progress.recent_asset_ids.length}
      <ul class="flex gap-2 overflow-hidden" aria-label={t('Pictures just read')}>
        {#each job.progress.recent_asset_ids.slice(-8) as asset (asset)}
          <li class="shrink-0"><img src={thumbnail(asset)} alt="" class="h-16 w-16 rounded-lg object-cover" /></li>
        {/each}
      </ul>
    {/if}
  {/if}

  {#if output}
    <pre class="max-h-64 overflow-auto rounded-lg bg-gray-100 p-3 text-xs whitespace-pre-wrap dark:bg-gray-900">{output}</pre>
  {/if}

  <div class="flex flex-wrap items-center gap-2">
    <code class="min-w-0 flex-1 truncate rounded-md bg-gray-100 px-2 py-1 text-xs dark:bg-gray-900" title={job.command}>{job.command}</code>
    <Button size="small" variant="ghost" leadingIcon={mdiContentCopy} onclick={copy}>{copied ? t('Copied') : t('Copy as CLI command')}</Button>
    {#if job.status === 'running'}
      <Button size="small" variant="outline" color="danger" leadingIcon={mdiStop} onclick={onCancel}>{t('Cancel')}</Button>
    {/if}
  </div>
</section>

// docs-site/remotion/src/components/JobPanel.tsx
import React from "react";
import { Img, staticFile } from "remotion";
import { mdiContentCopy, mdiStop } from "@mdi/js";
import { UI } from "../theme";
import { Button, CommandLine, ProgressBar } from "./ui";

/** web/src/lib/JobPanel.svelte: a running job's stage, bar, count, estimate and the pictures just read. */
export const JobPanel: React.FC<{
  label: string;
  elapsed: string;
  command: string;
  fraction?: number;
  done?: number;
  total?: number;
  /** The stage's own estimate, already worded ("~12s left in this stage"). */
  remaining?: string;
  /** The pictures just read, oldest first; the panel shows the last eight. */
  pictures?: string[];
  /** The newest picture's entry, 0..1, so the strip slides rather than jumps. */
  arriving?: number;
  running?: boolean;
}> = ({
  label,
  elapsed,
  command,
  fraction = 0,
  done,
  total,
  remaining,
  pictures = [],
  arriving = 1,
  running = true,
}) => {
  const shown = pictures.slice(-8);
  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        gap: 16,
        border: `1px solid ${UI.gray200}`,
        borderRadius: 16,
        padding: 20,
      }}
    >
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
        }}
      >
        <span style={{ fontSize: 16, fontWeight: 500 }}>{label}</span>
        <span
          style={{
            fontSize: 14,
            color: UI.gray600,
            fontVariantNumeric: "tabular-nums",
          }}
        >
          {elapsed}
        </span>
      </div>

      {running && <ProgressBar fraction={fraction} />}
      {running && total !== undefined && (
        <div
          style={{
            fontSize: 14,
            color: UI.gray600,
            fontVariantNumeric: "tabular-nums",
          }}
        >
          {done ?? 0} of {total}
          {remaining ? ` · ${remaining}` : ""}
        </div>
      )}
      {running && shown.length > 0 && (
        <div
          style={{ display: "flex", gap: 8, overflow: "hidden", height: 64 }}
        >
          {shown.map((picture, i) => {
            const newest = i === shown.length - 1;
            return (
              <Img
                key={`${picture}-${pictures.length - shown.length + i}`}
                src={staticFile(picture)}
                style={{
                  width: 64,
                  height: 64,
                  flexShrink: 0,
                  borderRadius: 8,
                  objectFit: "cover",
                  opacity: newest ? arriving : 1,
                  transform: newest
                    ? `scale(${0.85 + 0.15 * arriving})`
                    : undefined,
                }}
              />
            );
          })}
        </div>
      )}

      <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
        <CommandLine style={{ flex: 1, minWidth: 0, padding: "4px 8px" }}>
          {command}
        </CommandLine>
        <Button size="small" variant="ghost" icon={mdiContentCopy}>
          Copy as CLI command
        </Button>
        {running && (
          <Button size="small" variant="outline" color="danger" icon={mdiStop}>
            Cancel
          </Button>
        )}
      </div>
    </div>
  );
};

/** The panel's own clock: "48s", then "1m 05s". */
export const elapsedLabel = (seconds: number) => {
  const whole = Math.max(0, Math.round(seconds));
  const minutes = Math.floor(whole / 60);
  return minutes
    ? `${minutes}m ${String(whole % 60).padStart(2, "0")}s`
    : `${whole}s`;
};
