// web/src/lib/RenderPanel.svelte
<script lang="ts">
  import { Button, Heading } from '@immich/ui';
  import { mdiMusicNote, mdiUpload } from '@mdi/js';
  import { page } from '$app/state';
  import { onMount } from 'svelte';
  import { api, post, type JobView } from './api';
  import type { components } from './api-types';
  import { t } from './i18n.svelte';
  import { followJob } from './job.svelte';
  import JobPanel from './JobPanel.svelte';

  type Revision = components['schemas']['Revision'];

  let { runId, revisions, current = null }: { runId: string; revisions: Revision[]; current?: number | null } = $props();

  let from = $state<number | null>(null);
  // The revision just saved or opened is the one the owner means to render.
  $effect(() => {
    if (current != null) from = current;
  });
  let title = $state('');
  let subtitle = $state('');
  let transition = $state('');
  let orientation = $state('');
  let resolution = $state('');
  let format = $state('');
  let quality = $state('');
  let scaleMode = $state('');
  // On unless the owner unticks them: a film reads better with its dates and places (owner, 28 Sep).
  let addDate = $state(true);
  let addPlace = $state(true);
  let privacy = $state(false);
  let naming = $state<'' | 'model' | 'rules'>('');
  let music = $state<string>('auto');
  let volume = $state(0.5);
  let upload = $state(false);
  let album = $state('');

  let job = $state<JobView | null>(null);
  let preview = $state<JobView | null>(null);
  let uploaded = $state<{ id: string; name: string } | null>(null);
  let problem = $state('');

  const previewTrack = $derived((preview?.meta?.music_id as string | undefined) ?? null);
  const field = 'rounded-lg border border-gray-300 bg-light px-3 py-2 dark:border-gray-700';
  const label = 'flex flex-col gap-1 text-sm font-medium';
  const orNull = (value: string) => value || null;

  // A reload mid-render comes back to the job still running for this cut, not to an empty form.
  onMount(() => {
    void api<JobView | null>('/jobs/active').then((running) => {
      if (!running || running.meta?.run_id !== runId) return;
      if (running.kind === 'render') follow(running, (update) => (job = update));
      if (running.kind === 'music') follow(running, (update) => (preview = update));
    });
    return () => streams.forEach((stop) => stop());
  });

  const streams: (() => void)[] = [];

  function follow(started: JobView, onUpdate: (update: JobView) => void) {
    onUpdate(started);
    streams.push(followJob(started.id, onUpdate));
  }

  async function render() {
    problem = '';
    const { status, body } = await post<JobView>(`/runs/${encodeURIComponent(runId)}/renders`, {
      revision: from,
      title: orNull(title),
      subtitle: orNull(subtitle),
      transition: orNull(transition),
      orientation: orNull(orientation),
      resolution: orNull(resolution),
      format: orNull(format),
      quality: orNull(quality),
      scale_mode: orNull(scaleMode),
      add_date: addDate,
      add_place: addPlace,
      privacy_mode: privacy,
      llm_title: naming === '' ? null : naming === 'model',
      music,
      music_volume: music === 'none' ? null : volume,
      upload_to_immich: upload,
      album: upload ? orNull(album) : null,
    });
    const started = status === 202 ? body : status === 409 ? body.job : null;
    if (!started) {
      problem = body.detail ?? t('The render could not start.');
      return;
    }
    follow(started, (update) => (job = update));
  }

  async function makePreview() {
    const { status, body } = await post<JobView>(`/runs/${encodeURIComponent(runId)}/music-preview`, {});
    const started = status === 202 ? body : status === 409 ? body.job : null;
    if (!started) return;
    follow(started, (update) => (preview = update));
  }

  async function sendFile(event: Event) {
    const file = (event.currentTarget as HTMLInputElement).files?.[0];
    if (!file) return;
    const body = new FormData();
    body.append('file', file);
    const response = await fetch('/api/v1/music', { method: 'POST', body });
    const answer = await response.json();
    if (!response.ok) {
      problem = answer.detail ? t(answer.detail) : t('That file is not an MP3, M4A or WAV');
      return;
    }
    uploaded = answer;
    music = answer.id;
  }

  async function cancel(target: JobView) {
    const stopped = (await post<JobView>(`/jobs/${encodeURIComponent(target.id)}/cancel`, {})).body;
    if (job?.id === stopped.id) job = stopped;
    if (preview?.id === stopped.id) preview = stopped;
  }
</script>

<section class="flex flex-col gap-4 border-t border-gray-200 pt-6 dark:border-gray-800" aria-label={t('Render')}>
  <Heading size="tiny" tag="h2">{t('Render')}</Heading>
  {#if job}
    <JobPanel {job} onCancel={() => job && cancel(job)} />
    {#if job.status === 'succeeded' && job.result_run_id}
      <!-- svelte-ignore a11y_media_has_caption -->
      <video class="w-full max-w-3xl rounded-2xl bg-black" controls preload="metadata" src={`/api/v1/runs/${encodeURIComponent(job.result_run_id)}/film`}></video>
      <a class="w-fit text-sm text-primary hover:underline" href={`/app/runs/${encodeURIComponent(job.result_run_id)}`}>{t('Open the film run')}</a>
    {/if}
  {/if}
  {#if !job || job.status !== 'running'}
    <form class="grid max-w-3xl gap-4 sm:grid-cols-2" onsubmit={(event) => { event.preventDefault(); void render(); }}>
      <label class={label}>{t('What to render')}
        <select class={field} bind:value={from}>
          <option value={null}>{t('The cut as chosen')}</option>
          {#each revisions as revision (revision.number)}<option value={revision.number}>{t('Revision {number}', { number: revision.number })}</option>{/each}
        </select>
      </label>
      <label class={label}>{t('Transition Style')}
        <select class={field} bind:value={transition}>
          <option value="">{t('As configured')}</option><option value="smart">{t('Smart (fades and cuts)')}</option>
          <option value="crossfade">{t('Crossfade')}</option><option value="cut">{t('Cut')}</option><option value="none">{t('None')}</option>
        </select>
      </label>
      <label class={label}>{t('Title (decided as generate decides when empty)')}<input class={field} bind:value={title} /></label>
      <label class={label}>{t('Subtitle')}<input class={field} bind:value={subtitle} /></label>
      {#if !title}
        <label class={label}>{t('Who names the film')}
          <select class={field} bind:value={naming}>
            <option value="">{t('As generate decides')}</option>
            <option value="model">{t('The model, when one is configured')}</option>
            <option value="rules">{t('The dates and places, never a model')}</option>
          </select>
        </label>
      {/if}
      <label class={label}>{t('Orientation')}
        <select class={field} bind:value={orientation}>
          <option value="">{t('Automatic')}</option><option value="landscape">{t('Landscape')}</option>
          <option value="portrait">{t('Portrait')}</option><option value="square">{t('Square')}</option>
        </select>
      </label>
      <label class={label}>{t('Resolution')}
        <select class={field} bind:value={resolution}>
          <option value="">{t('As configured')}</option><option value="auto">{t('Match the sources')}</option>
          <option value="4k">4K</option><option value="1080p">1080p</option><option value="720p">720p</option>
        </select>
      </label>
      <label class={label}>{t('Format')}
        <select class={field} bind:value={format}>
          <option value="">{t('As configured')}</option><option value="mp4">MP4 (H.264)</option>
          <option value="h265">MP4 (H.265)</option><option value="prores">MOV (ProRes)</option>
        </select>
      </label>
      <label class={label}>{t('Quality')}
        <select class={field} bind:value={quality}>
          <option value="">{t('As configured')}</option><option value="high">{t('High')}</option>
          <option value="medium">{t('Medium')}</option><option value="low">{t('Low')}</option>
        </select>
      </label>
      <label class={label}>{t('Scaling Mode')}
        <select class={field} bind:value={scaleMode}>
          <option value="">{t('As configured')}</option><option value="blur">{t('Blurred background')}</option><option value="fit">{t('Fit with bars')}</option>
        </select>
      </label>
      <div class="flex flex-col gap-2 text-sm">
        <label class="flex items-center gap-2"><input type="checkbox" bind:checked={addDate} />{t('Add date overlay')}</label>
        <label class="flex items-center gap-2"><input type="checkbox" bind:checked={addPlace} />{t('Caption clips with their place')}</label>
        <label class="flex items-center gap-2"><input type="checkbox" bind:checked={privacy} />{t('Privacy mode: blur every picture and scramble names')}</label>
      </div>

      <fieldset class="flex flex-col gap-3 sm:col-span-2">
        <legend class="mb-1 text-sm font-semibold">{t('Music')}</legend>
        <div class="flex flex-wrap gap-2 text-sm">
          <label class="flex items-center gap-2"><input type="radio" bind:group={music} value="auto" />{t('Automatic (as configured)')}</label>
          <label class="flex items-center gap-2"><input type="radio" bind:group={music} value="none" />{t('No music')}</label>
          {#if previewTrack}<label class="flex items-center gap-2"><input type="radio" bind:group={music} value={previewTrack} />{t('The previewed track')}</label>{/if}
          {#if uploaded}<label class="flex items-center gap-2"><input type="radio" bind:group={music} value={uploaded.id} />{uploaded.name}</label>{/if}
        </div>
        <div class="flex flex-wrap items-center gap-2">
          <!-- A preview is generated; with no generator configured there is nothing to ask. -->
          {#if page.data.session?.music_preview_offered}
            <Button size="small" variant="outline" leadingIcon={mdiMusicNote} disabled={preview?.status === 'running'} onclick={makePreview}>{t('Preview a track')}</Button>
          {/if}
          <label class="relative inline-flex cursor-pointer items-center gap-2 rounded-lg border border-gray-300 px-3 py-1.5 text-sm dark:border-gray-700">
            <svg viewBox="0 0 24 24" class="size-4 fill-current" aria-hidden="true"><path d={mdiUpload} /></svg>{t('Upload a track')}
            <input type="file" accept=".mp3,.m4a,.wav,audio/*" class="sr-only" onchange={sendFile} />
          </label>
        </div>
        {#if preview}
          {#if preview.status === 'running'}<JobPanel job={preview} onCancel={() => preview && cancel(preview)} />{/if}
          {#if previewTrack}<audio controls src={`/api/v1/music/${previewTrack}`} class="w-full max-w-md"></audio>{/if}
          {#if preview.status !== 'running' && !previewTrack}<JobPanel job={preview} onCancel={() => {}} />{/if}
        {/if}
        {#if music !== 'none'}
          <label class="flex items-center gap-3 text-sm">{t('Music volume:')}
            <input type="range" min="0" max="1" step="0.05" bind:value={volume} class="w-48" /><span class="tabular-nums">{Math.round(volume * 100)}%</span>
          </label>
        {/if}
      </fieldset>

      <div class="flex flex-col gap-2 sm:col-span-2">
        <label class="flex items-center gap-2 text-sm"><input type="checkbox" bind:checked={upload} />{t('Upload the film to Immich')}</label>
        {#if upload}<label class={label}>{t('Album name')}<input class={field} bind:value={album} placeholder={t('As configured')} /></label>{/if}
      </div>
      {#if problem}<p class="text-sm text-danger sm:col-span-2" role="alert">{problem}</p>{/if}
      <Button type="submit" class="w-fit">{t('Render')}</Button>
    </form>
  {/if}
</section>

// docs-site/remotion/src/components/RenderPanel.tsx
import React from "react";
import { Img, OffthreadVideo, staticFile } from "remotion";
import { mdiMusicNote, mdiPlay, mdiUpload } from "@mdi/js";
import { UI } from "../theme";
import { Mdi } from "./Mdi";
import { JobPanel } from "./JobPanel";
import { Button, Check, Field, Heading } from "./ui";

/**
 * web/src/lib/RenderPanel.svelte: what to render (the cut as chosen or a saved
 * revision) and how, then the render job, then the film on the page.
 */

export type RenderState = {
  revision: boolean;
  /** The "What to render" select, open with this option under the pointer. */
  open?: "cut" | "revision";
  addDate: boolean;
  renderPressed?: number;
  job?: { label: string; fraction: number; elapsed: string; done: boolean };
  /** The film element: its poster until playing, then the film from `from` seconds. */
  film?: { playing: boolean; from: number };
};

export const RENDER_COMMAND = (runId: string) =>
  `immich-memories runs render ${runId} --revision=1 --music-volume=0.5 --add-date`;

const Radio: React.FC<{ label: string; checked?: boolean }> = ({
  label,
  checked,
}) => (
  <div style={{ display: "flex", alignItems: "center", gap: 8, fontSize: 14 }}>
    <div
      style={{
        width: 14,
        height: 14,
        borderRadius: 999,
        border: `${checked ? 4 : 1}px solid ${checked ? UI.primary : "#767676"}`,
        boxSizing: "border-box",
      }}
    />
    {label}
  </div>
);

const Options: React.FC<{ hover: "cut" | "revision" }> = ({ hover }) => (
  <div
    style={{
      position: "absolute",
      top: 70,
      left: 0,
      right: 0,
      background: UI.light,
      border: `1px solid ${UI.gray300}`,
      borderRadius: 8,
      boxShadow: "0 8px 24px rgba(0,0,0,0.15)",
      padding: 4,
      zIndex: 5,
      fontSize: 15,
    }}
  >
    {(
      [
        ["cut", "The cut as chosen"],
        ["revision", "Revision 1"],
      ] as const
    ).map(([key, label]) => (
      <div
        key={key}
        style={{
          padding: "6px 10px",
          borderRadius: 5,
          background: hover === key ? UI.primary : "transparent",
          color: hover === key ? UI.light : UI.dark,
        }}
      >
        {label}
      </div>
    ))}
  </div>
);

const Form: React.FC<{ state: RenderState }> = ({ state }) => (
  <div style={{ display: "grid", gridTemplateColumns: "376px 376px", gap: 16 }}>
    <div style={{ position: "relative" }}>
      <Field
        label="What to render"
        value={state.revision ? "Revision 1" : "The cut as chosen"}
        select
        focused={state.open !== undefined}
      />
      {state.open && <Options hover={state.open} />}
    </div>
    <Field label="Transition Style" value="As configured" select />
    <Field label="Title (decided as generate decides when empty)" value="" />
    <Field label="Subtitle" value="" />
    <Field label="Who names the film" value="As generate decides" select />
    <Field label="Orientation" value="Automatic" select />
    <Field label="Resolution" value="As configured" select />
    <Field label="Format" value="As configured" select />
    <Field label="Quality" value="As configured" select />
    <Field label="Scaling Mode" value="As configured" select />
    <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
      <Check label="Add date overlay" checked={state.addDate} />
      <Check label="Caption clips with their place" />
      <Check label="Privacy mode: blur every picture and scramble names" />
    </div>
    <div />
    <div
      style={{
        gridColumn: "span 2",
        display: "flex",
        flexDirection: "column",
        gap: 12,
        height: 132,
      }}
    >
      <div style={{ fontSize: 14, fontWeight: 600 }}>Music</div>
      <div style={{ display: "flex", gap: 8 }}>
        <Radio label="Automatic (as configured)" checked />
        <Radio label="No music" />
      </div>
      <div style={{ display: "flex", gap: 8 }}>
        <Button size="small" variant="outline" icon={mdiMusicNote}>
          Preview a track
        </Button>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 8,
            border: `1px solid ${UI.gray300}`,
            borderRadius: 8,
            padding: "6px 12px",
            fontSize: 14,
          }}
        >
          <Mdi path={mdiUpload} size={16} />
          Upload a track
        </div>
      </div>
      <div
        style={{ display: "flex", alignItems: "center", gap: 12, fontSize: 14 }}
      >
        Music volume:
        <div
          style={{
            position: "relative",
            width: 192,
            height: 4,
            borderRadius: 2,
            background: UI.gray300,
          }}
        >
          <div
            style={{
              width: "50%",
              height: "100%",
              borderRadius: 2,
              background: UI.primary,
            }}
          />
          <div
            style={{
              position: "absolute",
              left: 88,
              top: -6,
              width: 16,
              height: 16,
              borderRadius: 999,
              background: UI.primary,
            }}
          />
        </div>
        <span>50%</span>
      </div>
    </div>
    <div style={{ gridColumn: "span 2" }}>
      <Check label="Upload the film to Immich" />
    </div>
    <Button pressed={state.renderPressed ?? 0}>Render</Button>
  </div>
);

/** The film element as the panel shows it once the render succeeded. */
const Film: React.FC<{ film: NonNullable<RenderState["film"]> }> = ({
  film,
}) => (
  <div
    style={{
      position: "relative",
      width: 768,
      height: 432,
      borderRadius: 16,
      overflow: "hidden",
      background: "#000",
    }}
  >
    {film.playing ? (
      <OffthreadVideo
        src={staticFile("output-preview.mp4")}
        startFrom={Math.round(film.from * 30)}
        muted
        style={{ width: "100%", height: "100%", objectFit: "contain" }}
      />
    ) : (
      <>
        {/* preload="metadata": the browser shows the film's first frame until Play. */}
        <Img
          src={staticFile("output-frame.jpg")}
          style={{ width: "100%", height: "100%", objectFit: "contain" }}
        />
        <div
          style={{
            position: "absolute",
            left: 16,
            bottom: 14,
            display: "flex",
            alignItems: "center",
            gap: 10,
            color: "#fff",
            fontSize: 12,
          }}
        >
          <Mdi path={mdiPlay} size={22} />
          0:00 / 1:02
        </div>
      </>
    )}
  </div>
);

export const RenderPanel: React.FC<{ runId: string; state: RenderState }> = ({
  runId,
  state,
}) => (
  <div
    style={{
      borderTop: `1px solid ${UI.gray200}`,
      paddingTop: 24,
      display: "flex",
      flexDirection: "column",
      gap: 16,
    }}
  >
    <Heading size="tiny">Render</Heading>
    {state.job && (
      <div style={{ width: 768 }}>
        <JobPanel
          label={state.job.done ? "The film is ready." : state.job.label}
          elapsed={state.job.elapsed}
          command={RENDER_COMMAND(runId)}
          fraction={state.job.fraction}
          running={!state.job.done}
        />
      </div>
    )}
    {state.job?.done && state.film && (
      <>
        <Film film={state.film} />
        <div style={{ fontSize: 14, color: UI.primary }}>Open the film run</div>
      </>
    )}
    {(!state.job || state.job.done) && <Form state={state} />}
  </div>
);
